"""Render digest as HTML email and send via SMTP."""

from __future__ import annotations

import logging
import smtplib
import uuid
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate
from pathlib import Path
from typing import Optional, Tuple

from jinja2 import Environment, FileSystemLoader

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent / "templates"


def render_digest(digest: dict, week_date: str | None = None) -> tuple[str, str]:
    """
    Render digest data into HTML and plain text.

    Returns:
        (html_content, plain_text_content)
    """
    if week_date is None:
        week_date = datetime.now().strftime("%B %d, %Y")

    subject = f"\U0001f4ec Debrief \u2014 Week of {week_date}"

    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=True)
    template = env.get_template("digest_email.html")

    html = template.render(
        subject=subject,
        highlights_intro=digest.get("highlights_intro", ""),
        sections=digest.get("sections", []),
    )

    # Plain text fallback
    lines = [subject, "", digest.get("highlights_intro", ""), ""]
    for section in digest.get("sections", []):
        relevance = section.get("relevance", "none")
        lines.append(f"[{relevance.upper()}] {section['newsletter_name']}")
        lines.append(f"  From: {section.get('sender', '')}")
        lines.append(f"  {section.get('summary', '')}")
        for link in section.get("key_links", []):
            lines.append(f"  - {link['text']}: {link['url']}")
        lines.append("")
    lines.append("---")
    lines.append("Generated by Debrief | Built by Andreas Puyskens | Powered by Claude")

    plain_text = "\n".join(lines)
    return html, plain_text


def send_digest(
    html: str,
    plain_text: str,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    recipients: list,
    sender_name: str = "Newsletter Digest",
    week_date: str | None = None,
) -> None:
    """Send the rendered digest email via SMTP with STARTTLS."""
    if isinstance(recipients, str):
        recipients = [recipients]

    if week_date is None:
        week_date = datetime.now().strftime("%B %d, %Y")

    subject = f"\U0001f4ec Debrief \u2014 Week of {week_date}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{sender_name} <{smtp_user}>"
    msg["To"] = ", ".join(recipients)
    msg["Date"] = formatdate(localtime=True)
    msg["Message-ID"] = f"<debrief-{uuid.uuid4()}@{smtp_user.split('@')[1]}>"

    msg.attach(MIMEText(plain_text, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    try:
        logger.info("Connecting to SMTP %s:%d", smtp_host, smtp_port)
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
        logger.info("Digest sent to %s", ", ".join(recipients))
    except smtplib.SMTPException as e:
        logger.error("SMTP send failed: %s", e)
        raise
